---
deployment:
  tasks:
    - /bin/mkdir -p /home1/juanurrego/reactappapplication.online/wp-content/themes/PersonalThemeNew
    - /bin/cp -rf * /home1/juanurrego/reactappapplication.online/wp-content/themes/PersonalThemeNew
    - /bin/ls -la /home1/juanurrego/reactappapplication.online/wp-content/themes/PersonalThemeNew
