---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/juanurrego/public_html/reactappapplication.online/wp-content/themes/PersonalThemeNew
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH
